/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangmangame.gui;

import hangmangame.HangmanGame;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Gopal
 */
public class hangman extends javax.swing.JFrame {

    //variables
    int totalclicked = 0;
    String word = "";
    int count_char = 0;
    int live = 5;
    String temp = "";
    int match = 0;
    char btnclicked[] = new char[26];
    int S = 0;

    //print function all main logic of code is here
    public int print(char ch) {
        //check if button is already clicked or not
        for (int i = 0; i < totalclicked; i++) {
            if (btnclicked[i] == ch) {
                return 0;
            }
        }
        //if not clicked then 
        btnclicked[totalclicked++] = ch;

        int flag = 0;
        char emp[] = new char[S * 2];
        //updating character guesed and storing it
        for (int i = 0; i < S * 2; i += 2) {
            emp[i] = temp.charAt(i);
            emp[i + 1] = ' ';
        }
        //checking character guesed wwith original word
        for (int i = 0; i < S; i++) {
            if (word.charAt(i) == ch) {
                emp[i * 2] = word.charAt(i);
                count_char++;
                flag = 1;
                match = 1;
            }
        }
        //decreasing live if wrong guess
        if (flag == 0 && live > 0) {
            lives.setText(--live + "");
        }
        //if wrong guessed andd lost all lives
        if (flag == 0 && live == 0) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Game over! start new game");
            hangman a = new hangman();
            a.setVisible(true);
            this.dispose();

        }

        temp = new String(emp);
        String string = new String(emp);

        //display guessed character to the text area
        DisplayText1.setText(string);
        //if word guessed correctly 
        if (count_char == S) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Congratulation! YOU WIN");
            hangman a = new hangman();
            a.setVisible(true);
            this.dispose();
        }
        return 1;
    }

    public hangman() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisplayText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DisplayText1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        lives = new javax.swing.JTextField();
        Abutton = new javax.swing.JButton();
        Bbutton = new javax.swing.JButton();
        Cbutton = new javax.swing.JButton();
        Dbutton = new javax.swing.JButton();
        Ebutton = new javax.swing.JButton();
        Fbutton = new javax.swing.JButton();
        Lbutton = new javax.swing.JButton();
        Rbutton = new javax.swing.JButton();
        Xbutton = new javax.swing.JButton();
        Wbutton = new javax.swing.JButton();
        Qbutton = new javax.swing.JButton();
        Kbutton = new javax.swing.JButton();
        Jbutton = new javax.swing.JButton();
        Ibutton = new javax.swing.JButton();
        Gbutton = new javax.swing.JButton();
        Hbutton = new javax.swing.JButton();
        Mbutton = new javax.swing.JButton();
        Nbutton = new javax.swing.JButton();
        Obutton = new javax.swing.JButton();
        Ubutton = new javax.swing.JButton();
        Vbutton = new javax.swing.JButton();
        Pbutton = new javax.swing.JButton();
        Tbutton = new javax.swing.JButton();
        Sbutton = new javax.swing.JButton();
        Ybutton = new javax.swing.JButton();
        Zbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmangame/title.png"))); // NOI18N

        DisplayText1.setEditable(false);
        DisplayText1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DisplayText1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DisplayText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayText1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lives left!");

        startButton.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        startButton.setText("New Game");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        quitButton.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        lives.setEditable(false);
        lives.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lives.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lives.setText("5");
        lives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livesActionPerformed(evt);
            }
        });

        Abutton.setBackground(new java.awt.Color(204, 255, 255));
        Abutton.setText("A");
        Abutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbuttonActionPerformed(evt);
            }
        });

        Bbutton.setBackground(new java.awt.Color(204, 255, 255));
        Bbutton.setText("B");
        Bbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbuttonActionPerformed(evt);
            }
        });

        Cbutton.setBackground(new java.awt.Color(204, 255, 255));
        Cbutton.setText("C");
        Cbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbuttonActionPerformed(evt);
            }
        });

        Dbutton.setBackground(new java.awt.Color(204, 255, 255));
        Dbutton.setText("D");
        Dbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Dbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DbuttonActionPerformed(evt);
            }
        });

        Ebutton.setBackground(new java.awt.Color(204, 255, 255));
        Ebutton.setText("E");
        Ebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EbuttonActionPerformed(evt);
            }
        });

        Fbutton.setBackground(new java.awt.Color(204, 255, 255));
        Fbutton.setText("F");
        Fbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FbuttonActionPerformed(evt);
            }
        });

        Lbutton.setBackground(new java.awt.Color(204, 255, 255));
        Lbutton.setText("L");
        Lbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LbuttonActionPerformed(evt);
            }
        });

        Rbutton.setBackground(new java.awt.Color(204, 255, 255));
        Rbutton.setText("R");
        Rbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbuttonActionPerformed(evt);
            }
        });

        Xbutton.setBackground(new java.awt.Color(204, 255, 255));
        Xbutton.setText("X");
        Xbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XbuttonActionPerformed(evt);
            }
        });

        Wbutton.setBackground(new java.awt.Color(204, 255, 255));
        Wbutton.setText("W");
        Wbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WbuttonActionPerformed(evt);
            }
        });

        Qbutton.setBackground(new java.awt.Color(204, 255, 255));
        Qbutton.setText("Q");
        Qbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QbuttonActionPerformed(evt);
            }
        });

        Kbutton.setBackground(new java.awt.Color(204, 255, 255));
        Kbutton.setText("K");
        Kbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KbuttonActionPerformed(evt);
            }
        });

        Jbutton.setBackground(new java.awt.Color(204, 255, 255));
        Jbutton.setText("J");
        Jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbuttonActionPerformed(evt);
            }
        });

        Ibutton.setBackground(new java.awt.Color(204, 255, 255));
        Ibutton.setText("I");
        Ibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IbuttonActionPerformed(evt);
            }
        });

        Gbutton.setBackground(new java.awt.Color(204, 255, 255));
        Gbutton.setText("G");
        Gbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GbuttonActionPerformed(evt);
            }
        });

        Hbutton.setBackground(new java.awt.Color(204, 255, 255));
        Hbutton.setText("H");
        Hbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HbuttonActionPerformed(evt);
            }
        });

        Mbutton.setBackground(new java.awt.Color(204, 255, 255));
        Mbutton.setText("M");
        Mbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MbuttonActionPerformed(evt);
            }
        });

        Nbutton.setBackground(new java.awt.Color(204, 255, 255));
        Nbutton.setText("N");
        Nbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NbuttonActionPerformed(evt);
            }
        });

        Obutton.setBackground(new java.awt.Color(204, 255, 255));
        Obutton.setText("O");
        Obutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObuttonActionPerformed(evt);
            }
        });

        Ubutton.setBackground(new java.awt.Color(204, 255, 255));
        Ubutton.setText("U");
        Ubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbuttonActionPerformed(evt);
            }
        });

        Vbutton.setBackground(new java.awt.Color(204, 255, 255));
        Vbutton.setText("V");
        Vbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VbuttonActionPerformed(evt);
            }
        });

        Pbutton.setBackground(new java.awt.Color(204, 255, 255));
        Pbutton.setText("P");
        Pbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PbuttonActionPerformed(evt);
            }
        });

        Tbutton.setBackground(new java.awt.Color(204, 255, 255));
        Tbutton.setText("T");
        Tbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbuttonActionPerformed(evt);
            }
        });

        Sbutton.setBackground(new java.awt.Color(204, 255, 255));
        Sbutton.setText("S");
        Sbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbuttonActionPerformed(evt);
            }
        });

        Ybutton.setBackground(new java.awt.Color(204, 255, 255));
        Ybutton.setText("Y");
        Ybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YbuttonActionPerformed(evt);
            }
        });

        Zbutton.setBackground(new java.awt.Color(204, 255, 255));
        Zbutton.setText("Z");
        Zbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1067, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(Gbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Hbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Ibutton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(19, 19, 19)
                                                .addComponent(Kbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Lbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Abutton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Bbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Cbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Dbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(19, 19, 19)
                                                .addComponent(Ebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Fbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lives, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Mbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Nbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Obutton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(Pbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Qbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Rbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Ybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Zbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Sbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Tbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(Ubutton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Vbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addComponent(Wbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Xbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(239, 239, 239)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DisplayText1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Abutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Gbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ibutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Kbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Mbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Obutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Qbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(DisplayText1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lives, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ubutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Vbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Wbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Xbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Zbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(210, 210, 210))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void livesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_livesActionPerformed
//code for character buttons
    private void NbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NbuttonActionPerformed
        // TODO add your handling code here:

        if (print('n') != 0) {
            if (match == 0) {
                Nbutton.setBackground(Color.red);
            } else {
                match = 0;
                Nbutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_NbuttonActionPerformed
    //start new game button
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        //start new games     
        HangmanGame G = new HangmanGame();
        word = G.getWord();
        S = word.length();

        char emp[] = new char[S * 2];
        for (int i = 0; i < S * 2; i += 2) {
            emp[i] = '_';
            emp[i + 1] = ' ';
        }

        temp = new String(emp);
        String string = new String(emp);
        DisplayText1.setText(string);
    }//GEN-LAST:event_startButtonActionPerformed

    private void DisplayText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayText1ActionPerformed

    private void AbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbuttonActionPerformed
        // TODO add your handling code here:
        if (print('a') != 0) {
            if (match == 0) {
                Abutton.setBackground(Color.red);
            } else {
                match = 0;
                Abutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_AbuttonActionPerformed

    private void BbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbuttonActionPerformed
        // TODO add your handling code here:
        if (print('b') != 0) {
            if (match == 0) {
                Bbutton.setBackground(Color.red);
            } else {
                match = 0;
                Bbutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_BbuttonActionPerformed

    private void CbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbuttonActionPerformed
        // TODO add your handling code here:
        if (print('c') != 0) {
            if (match == 0) {
                Cbutton.setBackground(Color.red);
            } else {
                match = 0;
                Cbutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_CbuttonActionPerformed

    private void DbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DbuttonActionPerformed
        // TODO add your handling code here:
        if (print('d') != 0) {
            if (match == 0) {
                Dbutton.setBackground(Color.red);
            } else {
                match = 0;
                Dbutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_DbuttonActionPerformed

    private void EbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EbuttonActionPerformed
        // TODO add your handling code here:
        if (print('e') != 0) {
            if (match == 0) {
                Ebutton.setBackground(Color.red);
            } else {
                match = 0;
                Ebutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_EbuttonActionPerformed

    private void FbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FbuttonActionPerformed
        // TODO add your handling code here:
        if (print('f') != 0) {
            if (match == 0) {
                Fbutton.setBackground(Color.red);
            } else {
                match = 0;
                Fbutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_FbuttonActionPerformed

    private void GbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GbuttonActionPerformed
        // TODO add your handling code here:
        if (print('g') != 0) {
            if (match == 0) {
                Gbutton.setBackground(Color.red);
            } else {
                match = 0;
                Gbutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_GbuttonActionPerformed

    private void HbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HbuttonActionPerformed
        // TODO add your handling code here:
        if (print('h') != 0) {
            if (match == 0) {
                Hbutton.setBackground(Color.red);
            } else {
                match = 0;
                Hbutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_HbuttonActionPerformed

    private void IbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IbuttonActionPerformed
        // TODO add your handling code here:
        if (print('i') != 0) {
            if (match == 0) {
                Ibutton.setBackground(Color.red);
            } else {
                match = 0;
                Ibutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_IbuttonActionPerformed

    private void JbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbuttonActionPerformed
        // TODO add your handling code here:
        if (print('j') != 0) {
            if (match == 0) {
                Jbutton.setBackground(Color.red);
            } else {
                match = 0;
                Jbutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_JbuttonActionPerformed

    private void KbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KbuttonActionPerformed
        // TODO add your handling code here:
        if (print('k') != 0) {
            if (match == 0) {
                Kbutton.setBackground(Color.red);
            } else {
                match = 0;
                Kbutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_KbuttonActionPerformed

    private void LbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LbuttonActionPerformed
        // TODO add your handling code here:
        if (print('l') != 0) {
            if (match == 0) {
                Lbutton.setBackground(Color.red);
            } else {
                match = 0;
                Lbutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_LbuttonActionPerformed

    private void MbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MbuttonActionPerformed
        // TODO add your handling code here:M');
        if (print('m') != 0) {
            if (match == 0) {
                Mbutton.setBackground(Color.red);
            } else {
                match = 0;
                Mbutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_MbuttonActionPerformed

    private void ObuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObuttonActionPerformed
        // TODO add your handling code here:
        if (print('o') != 0) {
            if (match == 0) {
                Obutton.setBackground(Color.red);
            } else {
                match = 0;
                Obutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_ObuttonActionPerformed

    private void PbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PbuttonActionPerformed
        // TODO add your handling code here:
        if (print('p') != 0) {
            if (match == 0) {
                Pbutton.setBackground(Color.red);
            } else {
                match = 0;
                Pbutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_PbuttonActionPerformed

    private void QbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QbuttonActionPerformed
        // TODO add your handling code here:
        if (print('q') != 0) {
            if (match == 0) {
                Qbutton.setBackground(Color.red);
            } else {
                match = 0;
                Qbutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_QbuttonActionPerformed

    private void RbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbuttonActionPerformed
        // TODO add your handling code here:
        if (print('r') != 0) {
            if (match == 0) {
                Rbutton.setBackground(Color.red);
            } else {
                match = 0;
                Rbutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_RbuttonActionPerformed

    private void SbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbuttonActionPerformed
        // TODO add your handling code here:
        if (print('s') != 0) {
            if (match == 0) {
                Sbutton.setBackground(Color.red);
            } else {
                match = 0;
                Sbutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_SbuttonActionPerformed

    private void TbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbuttonActionPerformed
        if (print('t') != 0) {
            if (match == 0) {
                Tbutton.setBackground(Color.red);
            } else {
                match = 0;
                Tbutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_TbuttonActionPerformed

    private void UbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbuttonActionPerformed
        // TODO add your handling code here:
        if (print('c') != 0) {
            if (match == 0) {
                Ubutton.setBackground(Color.red);
            } else {
                match = 0;
                Ubutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_UbuttonActionPerformed

    private void VbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VbuttonActionPerformed
        // TODO add your handling code here:

        if (print('v') != 0) {
            if (match == 0) {
                Vbutton.setBackground(Color.red);
            } else {
                match = 0;
                Vbutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_VbuttonActionPerformed

    private void WbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WbuttonActionPerformed
        // TODO add your handling code here:
        if (print('w') != 0) {
            if (match == 0) {
                Wbutton.setBackground(Color.red);
            } else {
                match = 0;
                Wbutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_WbuttonActionPerformed

    private void XbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XbuttonActionPerformed
        // TODO add your handling code here:
        if (print('x') != 0) {
            if (match == 0) {
                Xbutton.setBackground(Color.red);
            } else {
                match = 0;
                Xbutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_XbuttonActionPerformed

    private void YbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YbuttonActionPerformed
        // TODO add your handling code here:
        if (print('y') != 0) {
            if (match == 0) {
                Ybutton.setBackground(Color.red);
            } else {
                match = 0;
                Ybutton.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_YbuttonActionPerformed

    private void ZbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZbuttonActionPerformed
        // TODO add your handling code here:
        if (print('c') != 0) {

            if (match == 0) {
                Zbutton.setBackground(Color.red);
            } else {
                match = 0;
                Zbutton.setBackground(Color.green);
            }
        }
        // Zbutton.setEnabled(false);
    }//GEN-LAST:event_ZbuttonActionPerformed
//exit button
    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
        JFrame jFrame = new JFrame();
        JOptionPane.showMessageDialog(jFrame, "Thanks for playing");
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hangman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Abutton;
    private javax.swing.JButton Bbutton;
    private javax.swing.JButton Cbutton;
    private javax.swing.JButton Dbutton;
    private javax.swing.JTextField DisplayText;
    private javax.swing.JTextField DisplayText1;
    private javax.swing.JButton Ebutton;
    private javax.swing.JButton Fbutton;
    private javax.swing.JButton Gbutton;
    private javax.swing.JButton Hbutton;
    private javax.swing.JButton Ibutton;
    private javax.swing.JButton Jbutton;
    private javax.swing.JButton Kbutton;
    private javax.swing.JButton Lbutton;
    private javax.swing.JButton Mbutton;
    private javax.swing.JButton Nbutton;
    private javax.swing.JButton Obutton;
    private javax.swing.JButton Pbutton;
    private javax.swing.JButton Qbutton;
    private javax.swing.JButton Rbutton;
    private javax.swing.JButton Sbutton;
    private javax.swing.JButton Tbutton;
    private javax.swing.JButton Ubutton;
    private javax.swing.JButton Vbutton;
    private javax.swing.JButton Wbutton;
    private javax.swing.JButton Xbutton;
    private javax.swing.JButton Ybutton;
    private javax.swing.JButton Zbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lives;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
